name: Push-to-EC2
on:
  push:
    branches:
      - feature/aula21-31

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./"
          REMOTE_HOST: "ec2-13-221-88-102.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html/praticandop3/"
          EXCLUDE: "/vendor/, /node_modules/, .env, /storage/logs/, /storage/framework/"

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-13-221-88-102.compute-1.amazonaws.com"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/praticandop3/

            mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs
            chmod -R 775 storage bootstrap/cache

            composer install --no-dev --optimize-autoloader --ignore-platform-reqs

            php artisan cache:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
